
<!-- Generated by ai2html v0.100.0 - 2024-07-31 22:03 -->
<!-- ai file: carlson.ai -->
<style lang="scss">
	#g-carlson-box ,
	#g-carlson-box .g-artboard {
		margin:0 auto;
	}
	#g-carlson-box p {
		margin:0;
	}
	#g-carlson-box .g-aiAbs {
		position:absolute;
	}
	#g-carlson-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
		height: 100%;
		background-size: contain;
		background-repeat: no-repeat;
	}
	#g-carlson-box .g-aiPointText p { white-space: nowrap; }
	#g-carlson-xs {
		position:relative;
		overflow:hidden;
	}
	#g-carlson-xs p {
		font-weight:400;
		line-height:17px;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(0,0,0);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		height:auto;
		position:static;
	}
	#g-carlson-xs .g-pstyle0 {
		text-align:center;
	}
	#g-carlson-sm {
		position:relative;
		overflow:hidden;
	}
	#g-carlson-sm p {
		font-weight:400;
		line-height:17px;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(0,0,0);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		height:auto;
		position:static;
	}
	#g-carlson-sm .g-pstyle0 {
		text-align:center;
	}
	#g-carlson-md {
		position:relative;
		overflow:hidden;
	}
	#g-carlson-md p {
		font-weight:400;
		line-height:17px;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(0,0,0);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		height:auto;
		position:static;
	}
	#g-carlson-md .g-pstyle0 {
		text-align:center;
	}
	#g-carlson-md .g-pstyle1 {
		line-height:13px;
		height:13px;
		opacity:0.87;
		font-size:11px;
		color:rgb(119,119,119);
	}

	/* Custom CSS */
.text {
}


</style>

<div id="g-carlson-box" bind:clientWidth={width}>

	<!-- Artboard: xs -->
{#if width && ( width >= 0 && width <510)}	<div id="g-carlson-xs" class="g-artboard" style="">
<div style="padding: 0 0 100.303% 0;"></div>
		<div id="g-carlson-xs-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }graphics/carlson-xs.png);"></div>		<div id="g-ai0-1" class="g-text-shadow g-aiAbs" style="top:74.0181%;left:82.3158%;margin-left:-9.2424%;width:18.4848%;">
			<p class="g-pstyle0">Chicago</p>
		</div>
	</div>
{/if}
	<!-- Artboard: sm -->
{#if width && ( width >= 510 && width <780)}	<div id="g-carlson-sm" class="g-artboard" style="">
<div style="padding: 0 0 102.451% 0;"></div>
		<div id="g-carlson-sm-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }graphics/carlson-sm.png);"></div>		<div id="g-ai1-1" class="g-text-shadow g-aiAbs" style="top:85.5502%;left:86.5295%;margin-left:-5.9804%;width:11.9608%;">
			<p class="g-pstyle0">Chicago</p>
		</div>
	</div>
{/if}
	<!-- Artboard: md -->
{#if width && (width >= 780)}	<div id="g-carlson-md" class="g-artboard" style="">
<div style="padding: 0 0 66.6667% 0;"></div>
		<div id="g-carlson-md-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }graphics/carlson-md.png);"></div>		<div id="g-ai2-1" class="g-text-shadow g-aiAbs" style="top:86.5385%;left:86.9365%;margin-left:-3.9103%;width:7.8205%;">
			<p class="g-pstyle0">Chicago</p>
		</div>
		<div id="g-ai2-2" class="g-map g-aiAbs g-aiPointText" style="top:98.8838%;margin-top:-7.2px;left:81.5337%;width:25px;">
			<p class="g-pstyle1"> </p>
		</div>
		<div id="g-ai2-3" class="g-map g-aiAbs g-aiPointText" style="top:98.8838%;margin-top:-7.2px;left:91.6749%;width:25px;">
			<p class="g-pstyle1"> </p>
		</div>
	</div>
{/if}
</div>

<script>
	export let assetsPath = './';
	let width = null;
import { onMount } from 'svelte';
export let onAiMounted = () => {};
onMount(() => {
  onAiMounted();
});

</script>
<!-- End ai2html - 2024-07-31 22:03 -->
