
<!-- Generated by ai2html v0.100.0 - 2024-08-04 15:22 -->
<!-- ai file: lowenstein.ai -->
<style lang="scss">
	#g-lowenstein-box ,
	#g-lowenstein-box .g-artboard {
		margin:0 auto;
	}
	#g-lowenstein-box p {
		margin:0;
	}
	#g-lowenstein-box .g-aiAbs {
		position:absolute;
	}
	#g-lowenstein-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
		height: 100%;
		background-size: contain;
		background-repeat: no-repeat;
	}
	#g-lowenstein-box .g-aiPointText p { white-space: nowrap; }
	#g-lowenstein-xs {
		position:relative;
		overflow:hidden;
	}
	#g-lowenstein-xs p {
		font-weight:400;
		line-height:17px;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(0,0,0);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		height:auto;
		position:static;
	}
	#g-lowenstein-xs .g-pstyle0 {
		text-align:center;
	}
	#g-lowenstein-sm {
		position:relative;
		overflow:hidden;
	}
	#g-lowenstein-sm p {
		font-weight:400;
		line-height:17px;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(0,0,0);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		height:auto;
		position:static;
	}
	#g-lowenstein-sm .g-pstyle0 {
		text-align:center;
	}
	#g-lowenstein-md {
		position:relative;
		overflow:hidden;
	}
	#g-lowenstein-md p {
		font-weight:400;
		line-height:17px;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(0,0,0);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		height:auto;
		position:static;
	}
	#g-lowenstein-md .g-pstyle0 {
		text-align:center;
	}

	/* Custom CSS */
.text {
}


</style>

<div id="g-lowenstein-box" bind:clientWidth={width}>

	<!-- Artboard: xs -->
{#if width && ( width >= 0 && width <510)}	<div id="g-lowenstein-xs" class="g-artboard" style="">
<div style="padding: 0 0 158.3333% 0;"></div>
		<div id="g-lowenstein-xs-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }graphics/lowenstein-xs.png);"></div>		<div id="g-ai0-1" class="g-text-shadow g-aiAbs" style="top:46.89%;left:82.3158%;margin-left:-9.2424%;width:18.4848%;">
			<p class="g-pstyle0">Chicago</p>
		</div>
	</div>
{/if}
	<!-- Artboard: sm -->
{#if width && ( width >= 510 && width <780)}	<div id="g-lowenstein-sm" class="g-artboard" style="">
<div style="padding: 0 0 102.451% 0;"></div>
		<div id="g-lowenstein-sm-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }graphics/lowenstein-sm.png);"></div>		<div id="g-ai1-1" class="g-text-shadow g-aiAbs" style="top:77.7033%;left:86.7255%;margin-left:-5.9804%;width:11.9608%;">
			<p class="g-pstyle0">Chicago</p>
		</div>
	</div>
{/if}
	<!-- Artboard: md -->
{#if width && (width >= 780)}	<div id="g-lowenstein-md" class="g-artboard" style="">
<div style="padding: 0 0 66.6667% 0;"></div>
		<div id="g-lowenstein-md-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }graphics/lowenstein-md.png);"></div>		<div id="g-ai2-1" class="g-text-shadow g-aiAbs" style="top:78.2692%;left:88.8596%;margin-left:-3.9103%;width:7.8205%;">
			<p class="g-pstyle0">Chicago</p>
		</div>
	</div>
{/if}
</div>

<script>
	export let assetsPath = './';
	let width = null;
import { onMount } from 'svelte';
export let onAiMounted = () => {};
onMount(() => {
  onAiMounted();
});

</script>
<!-- End ai2html - 2024-08-04 15:22 -->
