
<!-- Generated by ai2html v0.100.0 - 2024-08-05 16:19 -->
<!-- ai file: network.ai -->
<style lang="scss">
	#g-network-box ,
	#g-network-box .g-artboard {
		margin:0 auto;
	}
	#g-network-box p {
		margin:0;
	}
	#g-network-box .g-aiAbs {
		position:absolute;
	}
	#g-network-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
		height: 100%;
		background-size: contain;
		background-repeat: no-repeat;
	}
	#g-network-box .g-aiPointText p { white-space: nowrap; }
	#g-network-xs {
		position:relative;
		overflow:hidden;
	}
	#g-network-xs p {
		font-weight:300;
		line-height:14px;
		opacity:1;
		letter-spacing:0em;
		font-size:12px;
		text-align:left;
		color:rgb(0,0,0);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		height:auto;
		position:static;
	}
	#g-network-xs .g-pstyle0 {
		font-weight:700;
		line-height:19px;
		font-size:16px;
		text-align:center;
		color:rgb(255,255,255);
	}
	#g-network-xs .g-pstyle1 {
		font-weight:700;
		line-height:17px;
		font-size:14px;
		text-align:center;
	}
	#g-network-xs .g-pstyle2 {
		text-align:center;
	}
	#g-network-xs .g-pstyle3 {
		font-weight:700;
		line-height:17px;
		font-size:14px;
	}
	#g-network-xs .g-pstyle4 {
		font-weight:700;
		line-height:17px;
		font-size:14px;
		text-align:right;
	}
	#g-network-xs .g-pstyle5 {
		text-align:right;
	}
	#g-network-sm {
		position:relative;
		overflow:hidden;
	}
	#g-network-sm p {
		font-weight:700;
		line-height:17px;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(0,0,0);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		height:auto;
		position:static;
	}
	#g-network-sm .g-pstyle0 {
		line-height:19px;
		font-size:16px;
		text-align:center;
		color:rgb(255,255,255);
	}
	#g-network-sm .g-pstyle1 {
		text-align:center;
	}
	#g-network-sm .g-pstyle2 {
		text-align:right;
	}
	#g-network-sm .g-pstyle3 {
		font-weight:300;
		line-height:14px;
		font-size:12px;
		text-align:center;
	}
	#g-network-sm .g-pstyle4 {
		font-weight:300;
		line-height:14px;
		font-size:12px;
		text-align:right;
	}
	#g-network-sm .g-pstyle5 {
		font-weight:300;
		line-height:14px;
		font-size:12px;
	}
	#g-network-md {
		position:relative;
		overflow:hidden;
	}
	#g-network-md p {
		font-weight:700;
		line-height:17px;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(0,0,0);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		height:auto;
		position:static;
	}
	#g-network-md .g-pstyle0 {
		line-height:19px;
		font-size:16px;
		text-align:center;
		color:rgb(255,255,255);
	}
	#g-network-md .g-pstyle1 {
		text-align:center;
	}
	#g-network-md .g-pstyle2 {
		font-weight:300;
		line-height:14px;
		font-size:12px;
		text-align:center;
	}

	/* Custom CSS */
.text {
}


</style>

<div id="g-network-box" bind:clientWidth={width}>

	<!-- Artboard: xs -->
{#if width && ( width >= 0 && width <510)}	<div id="g-network-xs" class="g-artboard" style="">
<div style="padding: 0 0 187.8788% 0;"></div>
		<div id="g-network-xs-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }graphics/network-xs.png);"></div>		<div id="g-ai0-1" class="g-text g-aiAbs" style="top:2.7419%;left:49.4379%;margin-left:-6.6667%;width:13.3333%;">
			<p class="g-pstyle0">1</p>
		</div>
		<div id="g-ai0-2" class="g-text g-aiAbs" style="top:2.7419%;left:86.4554%;margin-left:-6.6667%;width:13.3333%;">
			<p class="g-pstyle0">4</p>
		</div>
		<div id="g-ai0-3" class="g-text g-aiAbs" style="top:8.5484%;left:49.5235%;margin-left:-16.3636%;width:32.7273%;">
			<p class="g-pstyle1">Aron Puretz</p>
		</div>
		<div id="g-ai0-4" class="g-text g-aiAbs" style="top:8.5484%;left:86.3949%;margin-left:-16.3636%;width:32.7273%;">
			<p class="g-pstyle1">Eli Puretz</p>
		</div>
		<div id="g-ai0-5" class="g-text g-aiAbs" style="top:11.7742%;left:49.4959%;margin-left:-29.5455%;width:59.0909%;">
			<p class="g-pstyle2">Owns APEX Equity</p>
		</div>
		<div id="g-ai0-6" class="g-text g-aiAbs" style="top:11.7742%;left:86.3803%;margin-left:-22.8788%;width:45.7576%;">
			<p class="g-pstyle2">Aron&rsquo;s son</p>
		</div>
		<div id="g-ai0-7" class="g-text g-aiAbs" style="top:11.9355%;left:23.6524%;margin-left:-6.6667%;width:13.3333%;">
			<p class="g-pstyle0">3</p>
		</div>
		<div id="g-ai0-8" class="g-text g-aiAbs" style="top:17.9032%;left:23.6471%;margin-left:-20.4545%;width:40.9091%;">
			<p class="g-pstyle1">Oron Zarum</p>
		</div>
		<div id="g-ai0-9" class="g-text g-aiAbs" style="top:25.1613%;left:11.5968%;margin-left:-6.6667%;width:13.3333%;">
			<p class="g-pstyle0">2</p>
		</div>
		<div id="g-ai0-10" class="g-text g-aiAbs" style="top:28.2258%;left:91.3157%;margin-left:-6.6667%;width:13.3333%;">
			<p class="g-pstyle0">6</p>
		</div>
		<div id="g-ai0-11" class="g-text g-aiAbs" style="top:30.8065%;left:2.1618%;width:50%;">
			<p class="g-pstyle3">Boruch &ldquo;Barry&rdquo; Drillman</p>
		</div>
		<div id="g-ai0-12" class="g-text g-aiAbs" style="top:34.0323%;left:2.1618%;width:52.1212%;">
			<p>New York real estate investor</p>
		</div>
		<div id="g-ai0-13" class="g-text g-aiAbs" style="top:34.3548%;right:-0.0171%;width:33.3333%;">
			<p class="g-pstyle4">JPC Charities</p>
		</div>
		<div id="g-ai0-14" class="g-text g-aiAbs" style="top:39.8387%;left:29.3776%;margin-left:-6.6667%;width:13.3333%;">
			<p class="g-pstyle0">5</p>
		</div>
		<div id="g-ai0-15" class="g-text g-aiAbs" style="top:40.3226%;left:91.0396%;margin-left:-6.6667%;width:13.3333%;">
			<p class="g-pstyle0">7</p>
		</div>
		<div id="g-ai0-16" class="g-text g-aiAbs" style="top:45.6452%;left:29.4154%;margin-left:-16.3636%;width:32.7273%;">
			<p class="g-pstyle1">Chaim Puretz</p>
		</div>
		<div id="g-ai0-17" class="g-text g-aiAbs" style="top:46.4516%;right:1.2121%;width:42.7273%;">
			<p class="g-pstyle4">Better Housing Foundation</p>
		</div>
		<div id="g-ai0-18" class="g-text g-aiAbs" style="top:49.0323%;left:29.4007%;margin-left:-22.8788%;width:45.7576%;">
			<p class="g-pstyle2">Aron&rsquo;s brother</p>
		</div>
		<div id="g-ai0-19" class="g-text g-aiAbs" style="top:62.9032%;left:49.4786%;margin-left:-27.2727%;width:54.5455%;">
			<p class="g-pstyle1">APEX Equity</p>
		</div>
		<div id="g-ai0-20" class="g-text g-aiAbs" style="top:65.9677%;left:49.4298%;margin-left:-29.5455%;width:59.0909%;">
			<p class="g-pstyle2">Controls APEX Chicago and Integra</p>
		</div>
		<div id="g-ai0-21" class="g-text g-aiAbs" style="top:79.5161%;left:7.6839%;width:54.5455%;">
			<p class="g-pstyle3">APEX Chicago IL, LLC</p>
		</div>
		<div id="g-ai0-22" class="g-text g-aiAbs" style="top:79.6774%;right:3.0937%;width:55.4545%;">
			<p class="g-pstyle4">Integra Affordable Management, LLC </p>
		</div>
		<div id="g-ai0-23" class="g-text g-aiAbs" style="top:82.5806%;left:7.6839%;width:45.7576%;">
			<p>Owner of Ellis Lakeview</p>
		</div>
		<div id="g-ai0-24" class="g-text g-aiAbs" style="top:85.4839%;right:3.7309%;width:52.7273%;">
			<p class="g-pstyle5">Manager of Ellis Lakeview</p>
		</div>
		<div id="g-ai0-25" class="g-text g-aiAbs" style="top:95.6452%;left:49.5056%;margin-left:-57.7273%;width:115.4545%;">
			<p class="g-pstyle1">Ellis Lakeview Apartments  </p>
		</div>
		<div id="g-ai0-26" class="g-text g-aiAbs" style="top:98.2258%;left:49.4378%;margin-left:-57.7273%;width:115.4545%;">
			<p class="g-pstyle2">4624 S. Ellis Ave</p>
		</div>
	</div>
{/if}
	<!-- Artboard: sm -->
{#if width && ( width >= 510 && width <775)}	<div id="g-network-sm" class="g-artboard" style="">
<div style="padding: 0 0 121.5686% 0;"></div>
		<div id="g-network-sm-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }graphics/network-sm.png);"></div>		<div id="g-ai1-1" class="g-text g-aiAbs" style="top:5.1613%;left:47.3832%;margin-left:-4.3137%;width:8.6275%;">
			<p class="g-pstyle0">1</p>
		</div>
		<div id="g-ai1-2" class="g-text g-aiAbs" style="top:5.1613%;left:71.3357%;margin-left:-4.3137%;width:8.6275%;">
			<p class="g-pstyle0">4</p>
		</div>
		<div id="g-ai1-3" class="g-text g-aiAbs" style="top:5.1613%;left:90.7475%;margin-left:-4.3137%;width:8.6275%;">
			<p class="g-pstyle0">5</p>
		</div>
		<div id="g-ai1-4" class="g-text g-aiAbs" style="top:10.9677%;left:47.4386%;margin-left:-10.5882%;width:21.1765%;">
			<p class="g-pstyle1">Aron Puretz</p>
		</div>
		<div id="g-ai1-5" class="g-text g-aiAbs" style="top:10.9677%;left:71.2965%;margin-left:-10.5882%;width:21.1765%;">
			<p class="g-pstyle1">Eli Puretz</p>
		</div>
		<div id="g-ai1-6" class="g-text g-aiAbs" style="top:10.9677%;right:-0.0277%;width:21.1765%;">
			<p class="g-pstyle2">Chaim Puretz</p>
		</div>
		<div id="g-ai1-7" class="g-text g-aiAbs" style="top:11.2903%;left:23.1476%;margin-left:-4.3137%;width:8.6275%;">
			<p class="g-pstyle0">3</p>
		</div>
		<div id="g-ai1-8" class="g-text g-aiAbs" style="top:14.1935%;left:47.4207%;margin-left:-19.1176%;width:38.2353%;">
			<p class="g-pstyle3">Owns APEX Equity</p>
		</div>
		<div id="g-ai1-9" class="g-text g-aiAbs" style="top:14.1935%;left:71.2871%;margin-left:-14.8039%;width:29.6078%;">
			<p class="g-pstyle3">Aron&rsquo;s son</p>
		</div>
		<div id="g-ai1-10" class="g-text g-aiAbs" style="top:14.3548%;right:-0.0088%;width:29.6078%;">
			<p class="g-pstyle4">Aron&rsquo;s brother</p>
		</div>
		<div id="g-ai1-11" class="g-text g-aiAbs" style="top:17.2581%;left:23.1442%;margin-left:-13.2353%;width:26.4706%;">
			<p class="g-pstyle1">Oron Zarum</p>
		</div>
		<div id="g-ai1-12" class="g-text g-aiAbs" style="top:24.1935%;left:7.6736%;margin-left:-4.3137%;width:8.6275%;">
			<p class="g-pstyle0">2</p>
		</div>
		<div id="g-ai1-13" class="g-text g-aiAbs" style="top:29.8387%;left:0%;width:32.3529%;">
			<p>Boruch &ldquo;Barry&rdquo; Drillman</p>
		</div>
		<div id="g-ai1-14" class="g-text g-aiAbs" style="top:33.0645%;left:0%;width:33.7255%;">
			<p class="g-pstyle5">New York real estate investor</p>
		</div>
		<div id="g-ai1-15" class="g-text g-aiAbs" style="top:63.0645%;left:47.4095%;margin-left:-17.6471%;width:35.2941%;">
			<p class="g-pstyle1">APEX Equity</p>
		</div>
		<div id="g-ai1-16" class="g-text g-aiAbs" style="top:66.129%;left:47.3779%;margin-left:-19.1176%;width:38.2353%;">
			<p class="g-pstyle3">Controls APEX Chicago and Integra</p>
		</div>
		<div id="g-ai1-17" class="g-text g-aiAbs" style="top:70.1613%;left:89.8709%;margin-left:-4.3137%;width:8.6275%;">
			<p class="g-pstyle0">6</p>
		</div>
		<div id="g-ai1-18" class="g-text g-aiAbs" style="top:76.2903%;right:-0.011%;width:21.5686%;">
			<p class="g-pstyle2">JPC Charities</p>
		</div>
		<div id="g-ai1-19" class="g-text g-aiAbs" style="top:79.6774%;left:25.2526%;margin-left:-17.6471%;width:35.2941%;">
			<p class="g-pstyle1">APEX Chicago IL, LLC</p>
		</div>
		<div id="g-ai1-20" class="g-text g-aiAbs" style="top:79.8387%;left:68.3846%;margin-left:-17.7451%;width:35.4902%;">
			<p class="g-pstyle1">Integra Affordable Management, LLC </p>
		</div>
		<div id="g-ai1-21" class="g-text g-aiAbs" style="top:82.7419%;left:25.2723%;margin-left:-14.8039%;width:29.6078%;">
			<p class="g-pstyle3">Owner of Ellis Lakeview</p>
		</div>
		<div id="g-ai1-22" class="g-text g-aiAbs" style="top:84.0323%;left:89.6771%;margin-left:-4.3137%;width:8.6275%;">
			<p class="g-pstyle0">7</p>
		</div>
		<div id="g-ai1-23" class="g-text g-aiAbs" style="top:85.6452%;left:68.4139%;margin-left:-24.7059%;width:49.4118%;">
			<p class="g-pstyle3">Manager of Ellis Lakeview</p>
		</div>
		<div id="g-ai1-24" class="g-text g-aiAbs" style="top:90.3226%;right:0.0304%;width:35.2941%;">
			<p class="g-pstyle2">Better Housing Foundation</p>
		</div>
		<div id="g-ai1-25" class="g-text g-aiAbs" style="top:95.8065%;left:47.427%;margin-left:-37.3529%;width:74.7059%;">
			<p class="g-pstyle1">Ellis Lakeview Apartments  </p>
		</div>
		<div id="g-ai1-26" class="g-text g-aiAbs" style="top:98.3871%;left:47.3831%;margin-left:-37.3529%;width:74.7059%;">
			<p class="g-pstyle3">4624 S. Ellis Ave</p>
		</div>
	</div>
{/if}
	<!-- Artboard: md -->
{#if width && (width >= 775)}	<div id="g-network-md" class="g-artboard" style="">
<div style="padding: 0 0 80% 0;"></div>
		<div id="g-network-md-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }graphics/network-md.png);"></div>		<div id="g-ai2-1" class="g-text g-aiAbs" style="top:3.3871%;left:10.781%;margin-left:-2.8387%;width:5.6774%;">
			<p class="g-pstyle0">3</p>
		</div>
		<div id="g-ai2-2" class="g-text g-aiAbs" style="top:3.5484%;left:49.9727%;margin-left:-2.8387%;width:5.6774%;">
			<p class="g-pstyle0">1</p>
		</div>
		<div id="g-ai2-3" class="g-text g-aiAbs" style="top:3.5484%;left:72.4446%;margin-left:-2.8387%;width:5.6774%;">
			<p class="g-pstyle0">4</p>
		</div>
		<div id="g-ai2-4" class="g-text g-aiAbs" style="top:3.5484%;left:89.4769%;margin-left:-2.8387%;width:5.6774%;">
			<p class="g-pstyle0">5</p>
		</div>
		<div id="g-ai2-5" class="g-text g-aiAbs" style="top:9.3548%;left:50.0091%;margin-left:-6.9677%;width:13.9355%;">
			<p class="g-pstyle1">Aron Puretz</p>
		</div>
		<div id="g-ai2-6" class="g-text g-aiAbs" style="top:9.3548%;left:72.4189%;margin-left:-6.9677%;width:13.9355%;">
			<p class="g-pstyle1">Eli Puretz</p>
		</div>
		<div id="g-ai2-7" class="g-text g-aiAbs" style="top:9.3548%;left:89.493%;margin-left:-6.9677%;width:13.9355%;">
			<p class="g-pstyle1">Chaim Puretz</p>
		</div>
		<div id="g-ai2-8" class="g-text g-aiAbs" style="top:9.3548%;left:10.7788%;margin-left:-8.7097%;width:17.4194%;">
			<p class="g-pstyle1">Oron Zarum</p>
		</div>
		<div id="g-ai2-9" class="g-text g-aiAbs" style="top:12.5806%;left:49.9973%;margin-left:-12.5806%;width:25.1613%;">
			<p class="g-pstyle2">Owns APEX Equity</p>
		</div>
		<div id="g-ai2-10" class="g-text g-aiAbs" style="top:12.5806%;left:72.4127%;margin-left:-9.7419%;width:19.4839%;">
			<p class="g-pstyle2">Aron&rsquo;s son</p>
		</div>
		<div id="g-ai2-11" class="g-text g-aiAbs" style="top:12.7419%;left:89.4868%;margin-left:-9.7419%;width:19.4839%;">
			<p class="g-pstyle2">Aron&rsquo;s brother</p>
		</div>
		<div id="g-ai2-12" class="g-text g-aiAbs" style="top:22.5806%;left:23.8412%;margin-left:-2.8387%;width:5.6774%;">
			<p class="g-pstyle0">2</p>
		</div>
		<div id="g-ai2-13" class="g-text g-aiAbs" style="top:28.2258%;left:23.7765%;margin-left:-10.6452%;width:21.2903%;">
			<p class="g-pstyle1">Boruch &ldquo;Barry&rdquo; Drillman</p>
		</div>
		<div id="g-ai2-14" class="g-text g-aiAbs" style="top:31.4516%;left:23.7756%;margin-left:-11.0968%;width:22.1935%;">
			<p class="g-pstyle2">New York real estate investor</p>
		</div>
		<div id="g-ai2-15" class="g-text g-aiAbs" style="top:61.7742%;left:49.99%;margin-left:-11.6129%;width:23.2258%;">
			<p class="g-pstyle1">APEX Equity</p>
		</div>
		<div id="g-ai2-16" class="g-text g-aiAbs" style="top:64.8387%;left:49.9692%;margin-left:-12.5806%;width:25.1613%;">
			<p class="g-pstyle2">Controls APEX Chicago and Integra</p>
		</div>
		<div id="g-ai2-17" class="g-text g-aiAbs" style="top:66.7742%;left:87.7388%;margin-left:-2.8387%;width:5.6774%;">
			<p class="g-pstyle0">6</p>
		</div>
		<div id="g-ai2-18" class="g-text g-aiAbs" style="top:72.9032%;left:87.6674%;margin-left:-11.6129%;width:23.2258%;">
			<p class="g-pstyle1">JPC Charities</p>
		</div>
		<div id="g-ai2-19" class="g-text g-aiAbs" style="top:78.3871%;left:35.4093%;margin-left:-11.6129%;width:23.2258%;">
			<p class="g-pstyle1">APEX Chicago IL, LLC</p>
		</div>
		<div id="g-ai2-20" class="g-text g-aiAbs" style="top:78.5484%;left:63.793%;margin-left:-11.6774%;width:23.3548%;">
			<p class="g-pstyle1">Integra Affordable Management, LLC </p>
		</div>
		<div id="g-ai2-21" class="g-text g-aiAbs" style="top:80.6452%;left:87.6112%;margin-left:-2.8387%;width:5.6774%;">
			<p class="g-pstyle0">7</p>
		</div>
		<div id="g-ai2-22" class="g-text g-aiAbs" style="top:81.4516%;left:35.4223%;margin-left:-9.7419%;width:19.4839%;">
			<p class="g-pstyle2">Owner of Ellis Lakeview</p>
		</div>
		<div id="g-ai2-23" class="g-text g-aiAbs" style="top:84.3548%;left:63.8122%;margin-left:-16.2581%;width:32.5161%;">
			<p class="g-pstyle2">Manager of Ellis Lakeview</p>
		</div>
		<div id="g-ai2-24" class="g-text g-aiAbs" style="top:86.7742%;left:87.6674%;margin-left:-11.6129%;width:23.2258%;">
			<p class="g-pstyle1">Better Housing Foundation</p>
		</div>
		<div id="g-ai2-25" class="g-text g-aiAbs" style="top:94.5161%;left:50.0015%;margin-left:-24.5806%;width:49.1613%;">
			<p class="g-pstyle1">Ellis Lakeview Apartments  </p>
		</div>
		<div id="g-ai2-26" class="g-text g-aiAbs" style="top:97.0968%;left:49.9726%;margin-left:-24.5806%;width:49.1613%;">
			<p class="g-pstyle2">4624 S. Ellis Ave</p>
		</div>
	</div>
{/if}
</div>

<script>
	export let assetsPath = './';
	let width = null;
import { onMount } from 'svelte';
export let onAiMounted = () => {};
onMount(() => {
  onAiMounted();
});

</script>
<!-- End ai2html - 2024-08-05 16:19 -->
