
<!-- Generated by ai2html v0.100.0 - 2024-07-22 22:03 -->
<!-- ai file: network.ai -->
<style lang="scss">
	#g-network-box ,
	#g-network-box .g-artboard {
		margin:0 auto;
	}
	#g-network-box p {
		margin:0;
	}
	#g-network-box .g-aiAbs {
		position:absolute;
	}
	#g-network-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
		height: 100%;
		background-size: contain;
		background-repeat: no-repeat;
	}
	#g-network-box .g-aiPointText p { white-space: nowrap; }
	#g-network-xs {
		position:relative;
		overflow:hidden;
	}
	#g-network-sm {
		position:relative;
		overflow:hidden;
	}
	#g-network-md {
		position:relative;
		overflow:hidden;
	}
	#g-network-md p {
		font-family:FreightTextPro,Georgia,serif;
		font-weight:400;
		line-height:14px;
		opacity:1;
		letter-spacing:0em;
		font-size:12px;
		text-align:left;
		color:rgb(0,0,0);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		height:auto;
		position:static;
	}
	#g-network-md .g-pstyle0 {
		font-weight:700;
		line-height:17px;
		font-size:14px;
		text-align:center;
	}
	#g-network-md .g-pstyle1 {
		text-align:center;
	}
	#g-network-md .g-pstyle2 {
		font-weight:300;
		text-align:center;
	}

	/* Custom CSS */
.text {
}


</style>

<div id="g-network-box" bind:clientWidth={width}>

	<!-- Artboard: xs -->
{#if width && ( width >= 0 && width <510)}	<div id="g-network-xs" class="g-artboard" style="">
<div style="padding: 0 0 187.8788% 0;"></div>
		<div id="g-network-xs-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }/network-xs.png);"></div>	</div>
{/if}
	<!-- Artboard: sm -->
{#if width && ( width >= 510 && width <780)}	<div id="g-network-sm" class="g-artboard" style="">
<div style="padding: 0 0 121.5686% 0;"></div>
		<div id="g-network-sm-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }/network-sm.png);"></div>	</div>
{/if}
	<!-- Artboard: md -->
{#if width && (width >= 780)}	<div id="g-network-md" class="g-artboard" style="">
<div style="padding: 0 0 79.4872% 0;"></div>
		<div id="g-network-md-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }/network-md.png);"></div>		<div id="g-ai2-1" class="g-text g-aiAbs" style="top:9.3548%;left:50.0091%;margin-left:-6.9231%;width:13.8462%;">
			<p class="g-pstyle0">Aron Puretz</p>
		</div>
		<div id="g-ai2-2" class="g-white-bg g-aiAbs" style="top:12.4194%;left:49.9766%;margin-left:-12.1154%;width:24.2308%;">
			<p class="g-pstyle1">2022 HUD Investigation: Aron Puretz and his company Apex Equity control both Integra and Apex Chicago. Federal authorities said earlier this year JPC Charities was created and managed by Aron &ldquo;for the purpose of receiving tax-exempt status for properties.&rdquo; He pled guilty to mortgage fraud conspiracy.</p>
		</div>
		<div id="g-ai2-3" class="g-text g-aiAbs" style="top:20.1613%;left:21.1241%;margin-left:-10.5769%;width:21.1538%;">
			<p class="g-pstyle0">Baruch &ldquo;Barry&rdquo; Drillman</p>
		</div>
		<div id="g-ai2-4" class="g-text g-aiAbs" style="top:21.129%;left:74.3265%;margin-left:-6.9231%;width:13.8462%;">
			<p class="g-pstyle0">Eli Puretz</p>
		</div>
		<div id="g-ai2-5" class="g-text g-aiAbs" style="top:23.3871%;left:21.1567%;margin-left:-9.6795%;width:19.359%;">
			<p class="g-pstyle2">Primary owner of Apex</p>
		</div>
		<div id="g-ai2-6" class="g-text g-aiAbs" style="top:24.5161%;left:74.3203%;margin-left:-9.6795%;width:19.359%;">
			<p class="g-pstyle2">Aron&rsquo;s son</p>
		</div>
		<div id="g-ai2-7" class="g-text g-aiAbs" style="top:34.5161%;left:86.8039%;margin-left:-6.9231%;width:13.8462%;">
			<p class="g-pstyle0">Chaim Puretz</p>
		</div>
		<div id="g-ai2-8" class="g-text g-aiAbs" style="top:37.9032%;left:86.7977%;margin-left:-9.6795%;width:19.359%;">
			<p class="g-pstyle2">Aron&rsquo;s brother</p>
		</div>
		<div id="g-ai2-9" class="g-text g-aiAbs" style="top:44.0323%;left:28.3379%;margin-left:-8.6538%;width:17.3077%;">
			<p class="g-pstyle0">Oron Zarum</p>
		</div>
		<div id="g-ai2-10" class="g-text g-aiAbs" style="top:51.6129%;left:46.7849%;margin-left:-11.5385%;width:23.0769%;">
			<p class="g-pstyle0">JPC Charities</p>
		</div>
		<div id="g-ai2-11" class="g-text g-aiAbs" style="top:55.3226%;left:61.7849%;margin-left:-11.5385%;width:23.0769%;">
			<p class="g-pstyle0">Better Housing Foundation</p>
		</div>
		<div id="g-ai2-12" class="g-text g-aiAbs" style="top:72.7419%;left:35.5029%;margin-left:-11.5385%;width:23.0769%;">
			<p class="g-pstyle0">APEX Chicago IL, LLC</p>
		</div>
		<div id="g-ai2-13" class="g-text g-aiAbs" style="top:72.9032%;left:63.9475%;margin-left:-16.9231%;width:33.8462%;">
			<p class="g-pstyle0">Integra </p>
		</div>
		<div id="g-ai2-14" class="g-text g-aiAbs" style="top:75.8065%;left:35.5157%;margin-left:-9.6795%;width:19.359%;">
			<p class="g-pstyle2">Owner of Ellis Lakeview</p>
		</div>
		<div id="g-ai2-15" class="g-text g-aiAbs" style="top:75.9677%;left:63.9732%;margin-left:-16.1538%;width:32.3077%;">
			<p class="g-pstyle2">Manager of Ellis Lakeview</p>
		</div>
		<div id="g-ai2-16" class="g-text g-aiAbs" style="top:88.871%;left:50.0015%;margin-left:-24.4231%;width:48.8462%;">
			<p class="g-pstyle0">Ellis Lakeview Apartments  </p>
		</div>
		<div id="g-ai2-17" class="g-text g-aiAbs" style="top:91.4516%;left:49.9728%;margin-left:-24.4231%;width:48.8462%;">
			<p class="g-pstyle2">4624 S. Ellis Ave</p>
		</div>
	</div>
{/if}
</div>

<script>
	export let assetsPath = './';
	let width = null;
import { onMount } from 'svelte';
export let onAiMounted = () => {};
onMount(() => {
  onAiMounted();
});

</script>
<!-- End ai2html - 2024-07-22 22:03 -->
