on: [workflow_dispatch]
jobs:
  get-google:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Fetch latest text from Google
    steps:
      - name: Create env
        run: echo "${{ secrets.ENV_FILE }}" > .env
      - name: Fetch latest Google text
        run: node --env-file=.env ./bin/google/index.cjs
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Run your project's build step
      # - name: Build
      #   run: npm install && npm run build
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: YOUR_PROJECT_NAME # e.g. 'my-project'
          directory: YOUR_DIRECTORY_OF_STATIC_ASSETS # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
