on: [workflow_dispatch]
jobs:
  get-google:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Fetch latest text from Google
    steps:
      - name: Fetch latest Google text
        env: # Or as an environment variable
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_CONSUMER_SECRET: ${{ secrets.GOOGLE_OAUTH_CONSUMER_SECRET }}
          GOOGLE_OAUTH_REDIRECT_URI: ${{ secrets.GOOGLE_OAUTH_REDIRECT_URI }}
        run: node bin/google/index.cjs
