on: [workflow_dispatch]
jobs:
  get-google:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Fetch latest text from Google
    steps:
      - name: Create env
        run: echo "${{ secrets.ENV }}" > .env
      - name: Fetch latest Google text
        run: node --env-file=.env ./bin/google/index.cjs
