on: [workflow_dispatch]
jobs:
  get-google:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Fetch latest text from Google
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: configure git
        run: git config user.email s.w.hart22@gmail.com && git config user.name swhart22
      - name: Fetch latest Google text
        env: # Or as an environment variable
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_CONSUMER_SECRET: ${{ secrets.GOOGLE_OAUTH_CONSUMER_SECRET }}
          GOOGLE_OAUTH_REDIRECT_URI: ${{ secrets.GOOGLE_OAUTH_REDIRECT_URI }}
        run: npm install && node ./bin/google/index.cjs
      - name: Build
        run: npm install && npm run build
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: iw-evictions-graphics-cf # e.g. 'my-project'
          directory: .svelte-kit/cloudflare # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Create dist folder for upload
        run: |
          mkdir ./.svelte-kit/evictions
          cp -a ./.svelte-kit/cloudflare/. ./.svelte-kit/evictions/
          zip -r ./.svelte-kit/evictions.zip ./.svelte-kit/evictions/
          mv ./.svelte-kit/evictions.zip ./
      - name: set origin
        run: git remote set-url origin https://${{ secrets.GIT_TOKEN }}@github.com/swhart22/iw-evictions-graphics-cf.git
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit --allow-empty -m "Republish from Github Action"
      - name: fetch from master
        run: git fetch origin main
      - name: push code to main
        env: 
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: git push origin HEAD:main
      
        
        
